name: ci

on: [push, pull_request]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Caching dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: npm-packages-${{ hashFiles('**/package-lock.json')}}

      - name: Install dependencies
          if: steps.cache.outputs.cache-hit == false
          run: npm ci

      - name: Build
        run: npm run build
